# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: "target/app.jar"
        if-no-files-found: error

  bundle-app-windows:
    runs-on: windows-latest
    needs:
      - build-jar

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4

      - name: Download and build go-java-launcher
        run: |
          git clone --depth 1 --branch v0.0.4 https://github.com/celedev97/go-java-launcher
          cd go-java-launcher
          make windows
          cd $GITHUB_WORKSPACE

      - name: Copy artifact
        run: |
          cp go-java-launcher/bin/go-java-launcher_windows.exe launcher.exe

      - name: Create go-java.json
        run: |
          echo '{"javaVersion":21,"launch":"./app.jar"}' > go-java.json

      - name: Save bundle
        uses: actions/upload-artifact@v3
        with:
          name: windows_build
          path: |
            launcher.exe
            go-java.json
            app.jar

  bundle-app-linux:
    runs-on: ubuntu-latest
    needs:
      - build-jar

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      - name: Setup xorg-dev
        run: sudo apt-get install xorg-dev -y

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4

      - name: Download and build go-java-launcher
        run: |
          git clone --depth 1 --branch v0.0.4 https://github.com/celedev97/go-java-launcher
          cd go-java-launcher
          make linux
          cd $GITHUB_WORKSPACE

      - name: Copy artifact
        run: |
          cp go-java-launcher/bin/go-java-launcher_linux launcher

      - name: Create go-java.json
        run: |
          echo '{"javaVersion":21,"launch":"./app.jar"}' > go-java.json

      - name: Save bundle
        uses: actions/upload-artifact@v3
        with:
          name: linux_build
          path: |
            launcher
            go-java.json
            app.jar




